### ISSUE TITLE
Run errors, trying multiple syntaxes

### ISSUE THREAD

**Issue by jhaddix** [Static-Flow/gf#1]
Trying to run the tool with the provided readme syntax and am getting:

```
root@TBox4:~# cat /root/hunter_out/PROBES.lst | gofingerprint -fingerprints /root/tools/gofingerprint/fingerprints/fingerprints.json
Started 20 workers!
open : no such file or directory
2020/08/08 00:55:06 invalid argument
```

also tried:

```
root@TBox4:~# cat /root/hunter_out/PROBES.lst | gofingerprint -fingerprints /root/tools/gofingerprint/fingerprints/fingerprints.json -o test
flag provided but not defined: -o
Usage of gofingerprint:
  -badpath string
        The intentional 404 path to hit each target with to get a response.
  -body string
        Data to send in the request body
  -debug
        Enable to see any errors with fetching targets
  -fingerprints string
        JSON file containing fingerprints to search for.
  -method string
        which HTTP request to make the request with (default "GET")
  -queue int
        Queue size to pool jobs (default 100000)
  -target string
        Target file with hosts to fingerprint
  -timeout int
        timeout for connecting to servers (default 10)
  -workers int
        Number of workers to process urls (default 20)
```

Any ideas?

**Comment by t0gu** [comment]
same with me.. @jhaddix  the *.lst* are domains or urls (https://jonh.doe) ?

**Comment by jhaddix** [comment]
URLs

**Comment by joeldeleep** [comment]
As mentioned by @jhaddix and @t0gu , I am having the same issue while running the script , but look at the code and help section passing the file using -target flag game me another error 
```bash

**Comment by joeldeleep** [comment]
As mentioned by @jhaddix and @t0gu I faced the same issue while providing it using cat command. But when I looked at the code and help section , it is saying about the target flag which accepts the input . I tried the target flag and it gave me another error 
```bash
gofingerprint -target file.txt -fingerprints fingerprints.json
Started 20 workers!
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.NewTarget(0xc00002d420, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/Tools/gofingerprint/cmd/gofingerprint/gofingerprint.go:126 +0x296
main.main()
	/roott/cmd/gofingerprint/gofingerprint.go:217 +0xa20
```

**Comment by rykkard** [comment]
good call @joeldeleep!  @jhaddix, stdin support was removed temporarily(?) at 0184dae9f20bbec30640944fad55f3c158d42e71, Currently gofingerprint only accepts the host list with the target flag 
`gofingerprint  -target <filename>`  

And if i'm not wrong the host list should have the format:
`domain,ip,port`

example:
```bash
$ cat target.txt 
hackerone.com,104.16.100.52,443

$ gofingerprint -fingerprints fingerprints.json -target target.txt -debug
Started 20 workers!
Done ingesting jobs
No Match
No Match
Done
```

**Comment by joeldeleep** [comment]
@rykkard  thanks for the update , I was having the domains without ip and port . The readme documentation is mentioning about the stdin as input and no information regarding how the domains should be .

**Comment by jhaddix** [comment]
now i need to write a parser to parse URLs to domain,ip,port =P
